# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check EnvHealth

# Set conditions for action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Set permissions as low as possible
permissions:
  contents: read
# A container that holds all instructions
jobs:

# The name of the job
  test-pixi:
  
    # Test pixi env on various platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    # Steps required to complete the test
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
        
    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.10.1
      with:
        pixi-version: v0.69.0
        activate-environment: true
        cache: true

    - name: Run a test command
      run: pixi run python -c "print('Pixi environment is healthy')"

  test-mamba:
    # Test mamba env on various platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    # Ensure that actions are run in non-base env    
    defaults:
      run:
        shell: bash -el {0}

      # Steps required to complete the test
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v7
          
      - name: Install Conda
        uses: mamba-org/setup-micromamba@v3
        with: 
          micromamba-version: latest
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
          
      - name: Install Pixi for export
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.69.0
          
      - name: Export pixi.lock as yml file
        run: pixi export conda-env > environment.yml 
          
      - name: Run a test command
        run: |
          micromamba create --name test-env --file environment.yml
          micromamba run -n test-env python -c "print('Mamba environment is healthy')"





